# Generated by Django 5.2.4 on 2025-07-26 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('credit', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('optional', 'Optional'), ('prerequisite', 'Prerequisite')], default='core', max_length=20)),
                ('description', models.TextField()),
                ('availability', models.BooleanField(default=True)),
                ('max_students', models.PositiveIntegerField(default=100, help_text='Maximum number of students')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='modules.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='students.student')),
            ],
            options={
                'ordering': ['-date_registered'],
                'unique_together': {('student', 'module')},
            },
        ),
    ]
